import { Link as RouterLink } from 'react-router-dom';
import React, { useState } from 'react';

import { toaster } from '../components/ui/toaster';

import GroupForm from '../components/Others/GroupForm';

import FormValidation from '../utils/FormValidation';
import GroupApi from '../services/GroupApi';



const items = [
    { value: "public", label: "public" },
    { value: "private", label: "private" },
];

const groupTypes = [
    { label: "study", value: "study" },
    { label: "project", value: "project" },
    { label: "research", value: "research" },
];

const groupTopics = [
    { label: "Mathematics", value: "math", type: "study" },
    { label: "Physics", value: "physics", type: "study" },
    { label: "Computer Science", value: "computer_science", type: "study" },
    { label: "AI & ML", value: "ai_ml", type: "research" },
];



const CreateGroup = () => {

    const user_id = localStorage.getItem('user_id');
    const [formData, setFormData] = useState({
        group_name: '',
        group_description: '',
        group_status: 'public',
        type: '',
        topics: [],
        group_image: '',
        user_id: user_id
    });
    const [file, setFile] = useState(null);
    const [errors, setErrors] = useState({});


    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData((prevData) => ({
            ...prevData,
            [name]: value,
        }));
    };

    const handleRadioChange = (value) => {
        setFormData({
            ...formData,
            group_status: value,
        });
    };

    const handleSelectType = (value) => {
        
        const singleValue = value[0]; 

        setFormData({
            ...formData,
            type: singleValue,
        });
    };
    
    
    const handleSelectTopics = (value) => {
       
        setFormData({
            ...formData,
            topics: value,
        });
    };
    
    const onSetFile = (file) => {
        setFile(file.files[0]);
    };

    const onClearFile = () => {
        setFile(null);
    };

    // Fetch api to store group data in database
    // Retrieve the image url for storage generated by database
    // Store the image using url in the database
    const handleSubmit = async (e) => {
        e.preventDefault();
        
        const formErrors = FormValidation.validateCreateGroupForm(formData);
        if(Object.keys(formErrors).length === 0) {
            console.log(formData);
            const result = await GroupApi.createGroup(formData);
            if(result.success) {
                toaster.create({
                    description: result.message,
                    type: "success",
                });
            } else {
                toaster.create({
                    description: result.message,
                    type: "error",
                });
            }
        } else {
            setErrors(formErrors);
        }
    
    };

    return (
        <GroupForm
            formData={formData}
            handleSubmit={(e)=> {e.preventDefault(); console.log(file);}}
            errors={errors}
            title="Create a new group"
            submitText="Create Group"
            items={items}
            groupTypes={groupTypes}
            groupTopics={groupTopics}
            handleChange={handleChange}
            handleRadioChange={handleRadioChange}
            handleSelectType={handleSelectType}
            handleSelectTopics={handleSelectTopics}
            onSetFile={onSetFile}
            onClearFile={onClearFile}
        />       
    );
};


export default CreateGroup;